l_polish:
### Mod Configuration Events ###

 xvcv_mdlc_abyss_access_possible.message.off: "§YAbyss§! Available Notification: §ROff§!"
 xvcv_mdlc_abyss_access_possible.message.on: "§YAbyss§! Available Notification: §GOn§!"
 xvcv_mdlc_civic_assimilating_swarm.message.off: "§Y$xvcv_mdlc_civic_assimilating_swarm$§! Civic Notification: §ROff§!"
 xvcv_mdlc_civic_assimilating_swarm.message.on: "§Y$xvcv_mdlc_civic_assimilating_swarm$§! Civic Notification: §GOn§!"
 xvcv_mdlc_config.1.1.off: "Species Conversion (Robot -> Machine): §ROff§!"
 xvcv_mdlc_config.1.1.on: "Species Conversion (Robot -> Machine): §GOn§!"
 xvcv_mdlc_config.1.2.off: "Species Conversion (Machine -> Robot): §ROff§!"
 xvcv_mdlc_config.1.2.on: "Species Conversion (Machine -> Robot): §GOn§!"
 xvcv_mdlc_config.1.3.off: "Species Mergence: §ROff§!"
 xvcv_mdlc_config.1.3.on: "Species Mergence: §GOn§!"
 xvcv_mdlc_config.1.4.off: "Automatic Pop Migration: §ROff§!"
 xvcv_mdlc_config.1.4.on: "Automatic Pop Migration: §GOn§!"
 xvcv_mdlc_config.1.desc: "This mod has utility features to help the player's gameplay. You can turn on or off each of them on this page.\n\nRobot -> Machine Species Conversion happens §Yannually§! only to §BMachine Intelligence§! Empire.\nMachine -> Robot Species Conversion happens §Yannually§! only to §GSynthetic Ascended§! Empire.\n\nSpecies Mergence will turn the Converted Species into our Founder Species, and will make all of our Machine and Robot Species become a Subspecies of our Founder Species §Yannually§!.\n\nAutomatic Pop Migration happens §Ymonthly§! only to §BMachine Intelligence§! or §GSynthetic Ascended§! Empire, and does not consider the target pop's habitability.\n\n§RTotal Jobless Pops§! in the Empire: §R[This.xvcv_mdlc_empire_all_unemployed_pops_count_var]§!\n§GTotal Jobs§! available in the Empire: §G[This.xvcv_mdlc_empire_all_free_jobs_count_var]§!\n§BTotal Available Housing§! in the Empire: §B[This.xvcv_mdlc_empire_all_free_housing_count_var]§!"
 xvcv_mdlc_config.1.name: "Mod Configurations: 1st Page"
 xvcv_mdlc_config.1.to_2nd_page: "Open The 2nd Page"
 xvcv_mdlc_config.1.to_credits_page: "Mod Credits & Thanks"
 xvcv_mdlc_config.2.desc: "Under certain situations, this mod will show notification messages for the player. You can make them appear or not on this page."
 xvcv_mdlc_config.2.name: "Mod Configurations: 2nd Page"
 xvcv_mdlc_config.2.to_1st_page: "Open The 1st Page"
 xvcv_mdlc_config.2.to_3_page: "Go to 3rd page"
 xvcv_mdlc_config.3_to_2nd_page: "Back to 2nd page"
 xvcv_mdlc_config.3_to_4_page: "Go to 4th page (Experimental features)"
 xvcv_mdlc_config.4_to_3nd_page: "Back to 3rd page"
 xvcv_mdlc_config.99.desc: "Credits and thanks to:\n\n- XVCV, original author of this mod\n- Legit-Rikk for reworking mute's Extended Machines, and for the World-Machine upgrades feature\n- FlantingCort, Krukal, and the Doves Localisation group for maintaining the Chinese translation of this mod\n\n- Stellaris Modding Den members in #modding-help and #moddev-forum for help figuring things out &\n- Supporters in the 'machine-robots-xpac' channel of the SMD, for your excitement and brainstorming and helping reign me in when I brainstorm too hard\n- Active commenters on the workshop page, thank you for your feedback and bug reports, I am doing my best with keeping up\n\n--Openly Retro, mod maintainer"
 xvcv_mdlc_config.99.name: "Mod Credits & Thanks"
 xvcv_mdlc_config.any_to_1st_page: "Back to main menu"
 xvcv_mdlc_config.message.off.tooltip: "This Feature is §RDeactivated§! now. Click to turn it §GOn§!."
 xvcv_mdlc_config.message.on.tooltip: "This Feature is §GActivated§! now. Click to turn it §ROff§!."
 xvcv_mdlc_decision_machine_cpu_project.message.off: "§Y$xvcv_mdlc_decision_machine_cpu_project$§! Decision Completion Notification: §ROff§!"
 xvcv_mdlc_decision_machine_cpu_project.message.on: "§Y$xvcv_mdlc_decision_machine_cpu_project$§! Decision Completion Notification: §GOn§!"
 xvcv_mdlc_decision_machine_ecu_project.message.off: "§Y$xvcv_mdlc_decision_machine_ecu_project$§! Decision Completion Notification: §ROff§!"
 xvcv_mdlc_decision_machine_ecu_project.message.on: "§Y$xvcv_mdlc_decision_machine_ecu_project$§! Decision Completion Notification: §GOn§!"
 xvcv_mdlc_decision_machine_ser_project.message.off: "§Y$xvcv_mdlc_decision_machine_ser_project$§! Decision Completion Notification: §ROff§!"
 xvcv_mdlc_decision_machine_ser_project.message.on: "§Y$xvcv_mdlc_decision_machine_ser_project$§! Decision Completion Notification: §GOn§!"
 xvcv_mdlc_decision_virtual_world_project.message.off: "§Y$xvcv_mdlc_decision_virtual_world_project$§! Decision Completion Notification: §ROff§!"
 xvcv_mdlc_decision_virtual_world_project.message.on: "§Y$xvcv_mdlc_decision_virtual_world_project$§! Decision Completion Notification: §GOn§!"
 xvcv_mdlc_pc_ringworld_automation_project.message.off: "§Y$xvcv_mdlc_pc_ringworld_automation_project$§! Decision Completion Notification: §ROff§!"
 xvcv_mdlc_pc_ringworld_automation_project.message.on: "§Y$xvcv_mdlc_pc_ringworld_automation_project$§! Decision Completion Notification: §GOn§!"
 xvcv_mdlc_r_unknown_core.message.off: "§Y$xvcv_mdlc_r_unknown_core$§! Relic Notification: §ROff§!"
 xvcv_mdlc_r_unknown_core.message.on: "§Y$xvcv_mdlc_r_unknown_core$§! Relic Notification: §GOn§!"
